### ISSUE TITLE
Cannot execute llvm code in polyglot workspace

### ISSUE THREAD

**Issue by Zenchess** [hpi-swa/trufflesqueak#108]
Hello.  I have graalsqueak running on linux, have installed all the 'gu available' packages for graalvm.  When I switch to LLVM in the polyglot workspace and try to execute the cell i get the following error:

Error: java.lang.IllegalArgumentException: Error evaluating the source.  The language llvm expects character based sources by default but a binary based source was provided.  Provide a character based source instead or specify a MIME type for the source.  Available MIME types for character based sources are [application/x-llvm-ir-bitcode-base64]/

I tried executing a Ruby cell and I believe it was working fine.

**Comment by fniephaus** [comment]
Hi @Zenchess,
Thanks for opening this issue. I believe this is a usability issue/limitation of [Sulong](https://github.com/oracle/graal/tree/master/sulong), GraalVM's LLVM interpreter. The polyglot workspace lists all supported languages dynamically, and Sulong does not seem to accept "eval string" requests through the Polyglot API. "eval file", on the other hand, works fine.

I'm curious, what did you try to evaluate in the polyglot workspace? C code, Rust code?

**Comment by Zenchess** [comment]
I tried evaluating this c code example from some graalvm webpage: 
```
#include <stdio.h>

int main() {
    printf("Hello from GraalVM!\n");
    return 0;
}
```
If I remember correctly any input into the llvm mode of the workspace will give the same error.  (Pretty sure i tried something simpler but i'll test again to make sure )

Btw, if graalvm for windows finally gets llvm-toolchain support, does this mean that I could use a c++ or C game engine in graalsqueak (in windows)?

**Comment by Zenchess** [comment]
I tried evaluating the same code as above in a file 'hello.c' and got the following error:
Polyglot eval: 'llvm' file: '/home/jacob/hello.c'

Error: com.oracle.truffle.llvm.runtime.except.LLVMParserException: The file
'/home/jacob/hello.c' is not a bitcode file nor an ELF or Mach-0 object file
with an embedded bitcode section.

Strangely, after trying to close the image, a new error popped up involving polyglot, and the image was unresponsive (alt . didnt pop up a debugger).

**Comment by fniephaus** [comment]
To run your example, you need to compile your C code to LLVM bitcode first:
```bash
"$GRAALVM_HOME/bin/gu" install llvm-toolchain
export LLVM_TOOLCHAIN=$("$GRAALVM_HOME/bin/lli" --print-toolchain-path)
$LLVM_TOOLCHAIN/clang your.c -lpolyglot-mock -o your.bc
```

Your should then be able to run the following in the workspace:
```smalltalk
(Polyglot eval: 'llvm' file: 'path/to/your.bc') main
```

For more information, visit https://www.graalvm.org/docs/reference-manual/polyglot/.

Let me know if you need any further help!

**Comment by fniephaus** [comment]
I should mention that we haven't done much with GraalSqueak and LLVM languages at this point, so you're one of the first to try this out! Please report any issues here (with steps to reproduce if you can), so we can fix them.

Also, the GraalVM knows about these usability issues in Sulong (the additional compilation step, the lack of support for `eval:string:`, etc...). Hopefully, things will improve sooner than later. If you have any further questions or suggestions wrt Sulong, you may also want to join the GraalVM Slack channel.
