### ISSUE TITLE
Run TruffleSqueak Command still says "GraalSqueak"

### ISSUE THREAD

**Issue by LeonBein** [hpi-swa/trufflesqueak#111]
In contrast to the README command for starting the image (`$GRAALVM_HOME/bin/trufflesqueak`), the image is still started with `$GRAALVM_HOME/bin/graalsqueak`. 

Probably either the readme should be reverted until the command is updated or the command should be updated.

**Comment by fniephaus** [comment]
Hi @LeonBein,
We've renamed the repository last night and are about to push a new release in the new few hours. Looks like you've decided to try TruffleSqueak in this very small window of consistency. Sorry for the inconvenience. Will be fixed with `1.0.0-rc9`.
