### ISSUE TITLE
Support multi-parameter constructors like multi-parameter blocks

### ISSUE THREAD

**Issue by LeonBein** [hpi-swa/trufflesqueak#113]
I would like to create `new SmalltalkObject(43, "Foobar")` like  `new OtherLanguageObject(43, "Foobar")`

Therefore, parameterized constructor calls should be mapped to Smalltalk calls, e.g. to `with:with:...` like Block calls are mapped to `value:value:....`

**Comment by fniephaus** [comment]
We discussed this offline: mapping constructor arguments to a magical call to `value:value:...` may not be intuitive and would lead to non-idiomatic Smalltalk code. More importantly, it is not clear whether `new SmalltalkArray(42)` should create an array with 42 (`#(42)`) or an array of size 42 (`#(nil nil ...)`). Therefore, I'd like to reject this proposal. Instead, #114 will be implemented soon.
