### ISSUE TITLE
DropPlugin: Drag and Drop into image does not work

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa/trufflesqueak#124]
Downloaded and installed TruffleSqueak today. Exciting project! But at least on Windows, I cannot drop a file into the image. Apparently, only `DragMove` events are generated, but `DragEnter`, `DragLeave`, and `DragDrop` are missing.

(If you have access, you might find the discussion in hpi-swa-lab/squeak#61 interesting, too.)

**Comment by fniephaus** [comment]
Thanks for filing this issue, @LinqLover. DNDing files into the image is currently not supported, the [`ClipboardExtendedPlugin`](https://github.com/hpi-swa/trufflesqueak/blob/a5537415ad34da28ebe6527631518eaa949d9821/src/de.hpi.swa.trufflesqueak/src/de/hpi/swa/trufflesqueak/nodes/plugins/ClipboardExtendedPlugin.java) is simply not implemented yet. It shouldn't be too hard to support it, let me know if you'd like to take up on the challenge. :)

**Comment by LinqLover** [comment]
This sounds definitively interesting, although I guess it will take me some more time since this is my first experience with the TruffleSqueak architecture at all. Can TruffleSqueak adapt plugins from the OpenSmalltalk-VM or does it completely rely on some kind of interface provided by the Graal VM? It's interesting to hear DND is connected to clipboard here; in OSVM, they use completely different interfaces for both purposes.

**Comment by fniephaus** [comment]
Oh, looks like I mixed something up. DND is provided through the [`DropPlugin`](https://github.com/hpi-swa/trufflesqueak/blob/ad61ebfad57cc8527f8789a2bc2afb47fa8304f3/src/de.hpi.swa.trufflesqueak/src/de/hpi/swa/trufflesqueak/nodes/plugins/DropPlugin.java#L25), and IIRC that was working a while ago. I hope this is the interface you were expecting. I should have another look on my system. Maybe it's just a Windows-related bug.

> Can TruffleSqueak adapt plugins from the OpenSmalltalk-VM or does it completely rely on some kind of interface provided by the Graal VM?

TruffleSqueak has new implementations of the VM plugins, all written in Java. So it doesn't rely on OSVM-specific nor on GraalVM-specific code.

**Comment by fniephaus** [comment]
Looks like I broke DND with https://github.com/hpi-swa/trufflesqueak/commit/61869694ef89d63af0192ddadd0202686e7f9b80?diff=unified#diff-94e14887428892fe45489070b0b83a73L436. I can reproduce with the following stack trace:

```
$ trufflesqueak images/dev.image
[trufflesqueak] Running Squeak/Smalltalk on GraalVM CE...
[trufflesqueak] Image loaded in 1565ms.
Exception in thread "AWT-EventQueue-0" java.lang.ArrayStoreException: arraycopy: type mismatch: can not copy java.io.File[] into java.lang.String[]
	at java.base/java.lang.System.arraycopy(Native Method)
	at java.base/java.util.Arrays.copyOf(Arrays.java:3722)
	at java.base/java.util.Arrays$ArrayList.toArray(Arrays.java:4341)
	at de.hpi.swa.trufflesqueak.io.SqueakDisplay$SqueakDropTargetAdapter.drop(SqueakDisplay.java:432)
	at java.desktop/java.awt.dnd.DropTarget.drop(DropTarget.java:452)
	at java.desktop/sun.awt.dnd.SunDropTargetContextPeer.processDropMessage(SunDropTargetContextPeer.java:547)
       ...
```

Let me push a fix....

**Comment by LinqLover** [comment]
> Oh, looks like I mixed something up. DND is provided through the DropPlugin, and IIRC that was working a while ago. I hope this is the interface you were expecting.

Yes, this looks much more like what I already knew from OSVM. Except that the Java implementation is much more beautiful to read! :-)

Great that you fixed it so fast. Can you give me a pointer how to install this patch on my machine? By reinstalling TruffleSqueak via the Graal VM Updater I only get the version "built on Jul 03 2020 13:18:29 CEST". Do I need to build from source in order to get the latest updates?

**Comment by fniephaus** [comment]
> Great that you fixed it so fast. Can you give me a pointer how to install this patch on my machine? By reinstalling TruffleSqueak via the Graal VM Updater I only get the version "built on Jul 03 2020 13:18:29 CEST". Do I need to build from source in order to get the latest updates?

Yes, you have to wait for the next release or build from source. To do the latter, you have to run something like this:
```
mkdir trufflesqueak-build
cd trufflesqueak-build
git clone https://github.com/graalvm/mx
git clone https://github.com/hpi-swa/trufflesqueak
cd trufflesqueak
../mx/mx --env trufflesqueak-jvm build --dependencies=SMALLTALK_INSTALLABLE_JAVA11
gu install -f -L "$(mx --env trufflesqueak-jvm paths SMALLTALK_INSTALLABLE_JAVA11)"
```

**Comment by LinqLover** [comment]
Thank you very much for your help! Actually, following your guide, in the second last line, it says `Could not find 'sdk:GRAAL_SDK' in GraalVM ('GRAALVM_C6C4856BB2_JAVA11')`; however with [these instructions](https://github.com/hpi-swa/trufflesqueak#building-from-source) I managed to build GraalSqueak and can confirm DnD works again! :-)
