### ISSUE TITLE
Getting a bigger window?

### ISSUE THREAD

**Issue by singpolyma-shopify** [hpi-swa/trufflesqueak#128]
Runs fine, polyglot stuff is super cool!  But when I resize the "host" window the squeak environment stays the same size... how do I make it bigger?

**Comment by fniephaus** [comment]
Thanks for reporting, @singpolyma-shopify! And sorry for the inconvenience.
If you resize the host window, the Squeak environment should be resized as well, which works fine on my MacBook. What OS and which version of TruffleSqueak and GraalVM are you using?

Thanks,
Fabio

**Comment by fniephaus** [comment]
I can't reproduce this. Please re-open if it is still an issue on your end.
