### ISSUE TITLE
Weird ClassNotFoundException mentioning Intellij 

### ISSUE THREAD

**Issue by janehmueller** [hpi-swa/trufflesqueak#129]
Using GraalVM 20.2.0 on MacOS Catalina (10.15.6) and having IntelliJ open with a Java project.
I was trying to instantiate Java classes in TruffleSqueak using `Java type: 'classname'` and at some point I noticed the following error message in my stdout. I'm not quite sure how to reprocude it.
```
Exception "java.lang.ClassNotFoundException: com/intellij/codeInsight/editorActions/FoldingData"while constructing DataFlavor for: application/x-java-jvm-local-objectref; class=com.intellij.codeInsight.editorActions.FoldingData
Exception "java.lang.ClassNotFoundException: com/intellij/codeInsight/editorActions/FoldingData"while constructing DataFlavor for: application/x-java-jvm-local-objectref; class=com.intellij.codeInsight.editorActions.FoldingData
```

**Comment by fniephaus** [comment]
Did this crash the image? Or just printed to stderr/stdout?

**Comment by janehmueller** [comment]
It was just printed to stderr/stdout

**Comment by fniephaus** [comment]
I think you're hitting this line:
https://github.com/hpi-swa/trufflesqueak/blob/4aa371a608bd73e9be1a6c65e727eb45370d23e8/src/de.hpi.swa.trufflesqueak/src/de/hpi/swa/trufflesqueak/io/SqueakDisplay.java#L431

Could you please verify?

**Comment by fniephaus** [comment]
I was able to reproduce and debug this. It's actually caused by:
https://github.com/graalvm/labs-openjdk-11/blob/e6d527daf65d565d52eefba34a6c94685b0fc26b/src/java.datatransfer/share/classes/java/awt/datatransfer/SystemFlavorMap.java#L404-L407

So not much we can do about this.
