### ISSUE TITLE
Can't instantiate TruffleSqueak Classes in Java 11

### ISSUE THREAD

**Issue by janehmueller** [hpi-swa/trufflesqueak#130]
Using GraalVM 20.2.0 on MacOS Catalina (10.15.6). When having TruffleSqueak open and trying the following command:
```smalltalk
Java type: 'de.hpi.swa.trufflesqueak.util.MiscUtils'
```
I get a Class not found error. This seems to be connected to the module system introducted in Java 9.

**Comment by fniephaus** [comment]
It seems this is caused by the recently introduced "class path isolation".
More information at: https://www.graalvm.org/graalvm-as-a-platform/implement-language/

**Comment by fniephaus** [comment]
Truffle is no longer using class path isolation, so I'm closing this as a won't fix.
