### ISSUE TITLE
Create TruffleSqueak standalone bundles

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/trufflesqueak#131]
It'd be good to have standalone bundles of TruffleSqueak (Linux/macOS/Windows), so that users can get started without having to know how to set up GraalVM and TruffleSqueak itself.

**Comment by jirir** [comment]
This would be great. Even for advanced users the need for manual GraalVM setup is often a deal breaker.

**Comment by fniephaus** [comment]
The first standalone bundles have been introduced some time ago via https://github.com/hpi-swa/trufflesqueak/commit/dba8c348ab3254cdb671fc58a021d4fe80fc52a8.
