### ISSUE TITLE
“graalvm-ce-java11-21.0.0” is damaged and can’t be opened

### ISSUE THREAD

**Issue by jirir** [hpi-swa/trufflesqueak#132]
On macOS 11.1

Executing:
/Applications/graalvm/graalvm-ce-java11-21.0.0/Contents/Home/bin/gu -C https://raw.githubusercontent.com/hpi-swa/trufflesqueak/master/gu-catalog.properties install smalltalk

says:
“graalvm-ce-java11-21.0.0” is damaged and can’t be opened. You should move it to the Trash.

**Comment by fniephaus** [comment]
Have you followed the instructions to remove the quarantine attribute on macOS?
https://github.com/oracle/graal/issues/1724#issuecomment-539503007

**Comment by jirir** [comment]
I see.
`sudo xattr -r -d com.apple.quarantine /path/to/graalvm`
makes it work.

**Comment by fniephaus** [comment]
Glad to hear it's working now.

**Comment by yingsu00** [comment]
@fniephaus @jirir I got the same problem. But running `sudo xattr -r -d com.apple.quarantine /path/to/graalvm` didn't help. I still get the error "graalvm-ce-java11-21.0.0” is damaged and can’t be opened". Anything else I can do?

**Comment by fniephaus** [comment]
`/path/to/graalvm` must point to the *root* directory of your GraalVM installation. Are you sure you didn't run the command against the GraalVM *home* directory, which ends with `.../Contents/Home`?

**Comment by yingsu00** [comment]
> `/path/to/graalvm` must point to the _root_ directory of your GraalVM installation. Are you sure you didn't run the command against the GraalVM _home_ directory, which ends with `.../Contents/Home`?

@fniephaus  Yes
```
$ sudo xattr -r -d com.apple.quarantine /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.0.0/Contents/Home
$ /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.0.0/Contents/Home/bin/java
Killed: 9
```
Not only the pop up window appears when I tried to run java, it also pops out from time to time
![Screen Shot 2021-02-09 at 11 55 44 PM](https://user-images.githubusercontent.com/33299678/107481037-63b0cc80-6b32-11eb-844d-55a7852267c2.png)

Anything else I can do? I tried to restart my mac and it's still the same. Please advise, thank you!

**Comment by fniephaus** [comment]
You did run it against home and not the root, so try this:
```
sudo xattr -r -d com.apple.quarantine /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.0.0
```

Does it work now?

**Comment by yingsu00** [comment]
> sudo xattr -r -d com.apple.quarantine /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.0.0

Oh this worked! Thank you Fabio! @fniephaus

**Comment by fniephaus** [comment]
Glad it's working now, I hope the GraalVM team will eventually sign their bundles and get them notarized.
