### ISSUE TITLE
TruffleSqueakLauncher consumes 100–300% CPU on macOS

### ISSUE THREAD

**Issue by jirir** [hpi-swa/trufflesqueak#133]
Activity Monitor shows about 100–300% CPU taken by `TruffleSqueakLauncher` after running:
`/Applications/graalvm/graalvm-ce-java11-20.2.0/Contents/Home/languages/smalltalk/bin/trufflesqueak`

Also the windows movement inside the `TruffleSqueak-20.2.0.image` is rather slow.

macOS 11.1
MacBook Pro Retina 13 mid 2014, 3GHz Dual-Core i7, 16GB RAM

**Comment by fniephaus** [comment]
Unfortunately, this is "normal" behavior. The load should go down after some seconds/minutes but will go up as you do more things in the Smalltalk environment. The reason for this is the Graal compiler "warming up" the environment in the background. You can see the compiler activity by running TruffleSqueak with "bin/trufflesqueak --engine.TraceCompilation".

**Comment by fniephaus** [comment]
We've written some of the limitations up in the [TruffleSqueak paper](https://fniephaus.com/2019/mplr19-graalsqueak.pdf) and the GraalVM team is very well aware of these issues. There's not much we can do about this at this point, but we are confident that the situation improves in the future.
