### ISSUE TITLE
Black box around cursor after change "Scale Factor" for Squeak6.0beta

### ISSUE THREAD

**Issue by dram** [hpi-swa/trufflesqueak#157]
When running Squeak6.0beta-21768 image in TruffleSqueak, if "Extras > Scale Factor" is changed (e.g. 125%), there will be a black box around cursor.

![1](https://user-images.githubusercontent.com/517130/169674486-a9bd1bc5-4eb6-4ae5-8230-db43f338c9d0.png)

**Comment by fniephaus** [comment]
Thanks for the report, @dram. I've also pushed a fix for this, which will ship with the next release.

**Comment by dram** [comment]
Fix confirmed, thanks!
