### ISSUE TITLE
trufflesqueak-launcher: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa/trufflesqueak#161]
I followed the installation instructions to install TruffleSqueak on my system:

Ubuntu 18.04
WSL1 on Windows 64 bit

After installing TruffleSqueak via `gu`, I cannot start it:

```
$ ./graalvm-ce-java17-linux-amd64-22.1.0/graalvm-ce-java17-22.1.0/bin/trufflesqueak --help
/mnt/c/Users/Christoph/Documents/graalvm/graalvm-ce-java17-linux-amd64-22.1.0/graalvm-ce-java17-22.1.0/languages/smalltalk/bin/trufflesqueak-launcher: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /mnt/c/Users/Christoph/Documents/graalvm/graalvm-ce-java17-linux-amd64-22.1.0/graalvm-ce-java17-22.1.0/languages/smalltalk/bin/trufflesqueak-launcher)
```

However, `libstdc++6` is installed:

```
$ sudo apt install libstdc++6
Reading package lists... Done
Building dependency tree
Reading state information... Done
libstdc++6 is already the newest version (8.4.0-1ubuntu1~18.04).
```

What extra packages and which versions of them do I have to install to get TruffleSqueak running?

**Comment by kolyaopahle** [comment]
As you are using wsl it might be worth a try to switch to a different os in wsl that supports the required glibc versions

**Comment by fniephaus** [comment]
I'm afraid TruffleSqueak is currently built on Ubuntu 20.04. I guess we could downgrade the runners to 18.04 but I'm not sure it's worth the effort. Maybe it's easy, maybe it's not depending on the dependencies :S

**Comment by LinqLover** [comment]
Thank you for the pointers! glibc version 3.4.26 was indeed not listed here. Finally got it working with this guide: https://askubuntu.com/a/1328208/1140486

Maybe either this link or a short hint about missing compatibility should be added somewhere to the installation instructions? :)
