### ISSUE TITLE
Missing `WindowEvent`s

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa/trufflesqueak#164]
See `WindowEvent>>#type` for all types that in theory should be supported. At the moment, I could only reproduce `windowClose`, `windowIconise`, and `windowActivated`. In practice, `windowDeactivated` is optional but would be nice-to-have since it is used to update the in-image keyboard focus depending on the host system. Actually, even OSVM (at least for Windows) seems to handle the 4 mentioned event types only, so `windowMetricChange`, `windowPaint`, and `windowChangedScreen` would be very optional.

Sounds like a very nice good first issue to be implemented in https://github.com/hpi-swa/trufflesqueak/blob/a068eca13ca09ac1de50bc4572dd53333fab8718/src/de.hpi.swa.trufflesqueak/src/de/hpi/swa/trufflesqueak/io/SqueakDisplay.java#L106. Maybe, at some free day in the summer ... :D

**Comment by fniephaus** [comment]
Yep, that'd be good to support. However, I'm not sure supporting something that OSVM doesn't is a good idea. I can tell from experience that this can cause weird issues, especially when code gets activated that usually isn't used at all.
