### ISSUE TITLE
No GUI shows up after loading TruffleSqueak-22.1.0.image on GraalVM CE 22.1

### ISSUE THREAD

**Issue by fifthmonk** [hpi-swa/trufflesqueak#168]
Nothing show up after loading the TruffleSqueak-22.1.0.image. I have no issue if running in headless mode. My machine is running on Mac OS 12.4 (x64).

**Comment by fifthmonk** [comment]
Please find the 2 console outputs below for your reference:

trufflesqueak --headless --code "1 + 2 * 3"
[trufflesqueak] Running TruffleSqueak-22.1.0.image on GraalVM CE (latency mode)...
[trufflesqueak] Image loaded in 1242ms.
[trufflesqueak] Evaluating '1 + 2 * 3'...
[trufflesqueak] Result: 9

trufflesqueak --headless --code "Smalltalk allClasses size"
[trufflesqueak] Running TruffleSqueak-22.1.0.image on GraalVM CE (latency mode)...
[trufflesqueak] Image loaded in 1337ms.
[trufflesqueak] Evaluating 'Smalltalk allClasses size'...
[trufflesqueak] Result: 3445

**Comment by fniephaus** [comment]
What does the output look like when you run without arguments / in headful mode? Also, could you try with GraalVM 22.0.0? Does TruffleSqueak 22.0.0 show a GUI?

**Comment by fifthmonk** [comment]
It does show the GUI if running with GraalVM 22.0.0.2. If running GraalVM 22.1

**Comment by fniephaus** [comment]
That's good to know! So it looks like there's a regression in 22.1.

Is there a `SqueakDebug.log` in the `graalvm-ce-java11-22.1.0/languages/smalltalk/resources` directory of your 22.1 installation? You can find the directory with `dirname "$(trufflesqueak --print-image-path)"`. If there's a `SqueakDebug.log`, could you please share it here?

**Comment by fifthmonk** [comment]
Unlike 22.0.0.2, there is no SqueakDebug.log file can be found under the directory /Library/Java/JavaVirtualMachines/graalvm-ce-java17-22.1.0/Contents/Home/languages/smalltalk/resources

**Comment by fniephaus** [comment]
Thanks for following up. I managed to reproduce this on macOS and traced it down to the language library launcher. Apparently, it does not allow AWT to function properly. I'm looking into a fix for the 22.2 release.
